#
adjective1 = input("Please enter an adjective: ")
adjective2 = input("Please enter another adjective: ")
noun1 = input("Please enter a noun: ")
noun2 = input("Please enter another noun: ")
plNoun1 = input("Please enter a plural noun: ")
game1 = input("Please enter a game: ")
plNoun2 = input("Please enter another plural noun: ")
verb1 = input("Please enter a verb ending in 'ing': ")
verb2 = input("Please enter another verb ending in 'ing': ")
plNoun3 = input("Please enter another plural noun: ")
verb3 = input("Please enter another verb ending in 'ing': ")
noun3 = input("Please enter another noun: ")
plant = input("Please enter a plant: ")
bodyPart = input("Please enter a body part: ")
place = input("Please enter a place: ")
verb4 = input("Please enter another verb ending in 'ing': ")
adjective3 = input("Please enter another adjective: ")
number = input("Please enter a number: ")
plNoun4 = input("Please enter a plural noun: ")

print(" ")
print(" ")
print("A vacation is when you take a trip to some " + (adjective1) + " place with your " + (adjective2) + " family.")
print("Usually you go someplace that is near a(n) " + (noun1) + " or up on a(n) " + (noun2) + ".")
print("A good vacation place is one where you can ride " + (plNoun1) + " or play " + (game1) + " or go hunting for " + (plNoun2) + ".")
print("I like to spend my time " + (verb1) + " or " + (verb2) + ".")
print("When parents go on vacation, they spend their time eating 3 " + (plNoun3) + " a day, fathers play golf, and mothers sit around " + (verb3) + ".")
print("Last year, my brother fell into a(n) " + (noun3) + " and got poison " + (plant) + " all over his " + (bodyPart) + ".")
print("This year, my family is going to (the) " + (place) + ", and I will practice " + (verb4) + ".")
print("Parents need vacations more than kids because they are very " + (adjective3) +
" and because they have to work " + (number) + "hours every day all year to make enough " + (plNoun4) + " to pay for the vacation.")
